#!/bin/bash
# Canon EOS 400D DIGITAL

bracket_mode() {
    local bracket_mode
    local exposure
    read bracket_mode exposure <<<$(exiftool -n -S -t -MakerNotes:ExposureMode -MakerNotes:AEBBracketValue "$1")
    
    if [ $bracket_mode = 2 ]; then
        echo "YES" "$exposure"
        return
    fi
    
    echo "NO" "0"
}

bracket_count() {
    echo 3
}