#!/bin/bash
# Canon EOS 5D Mark II
# Canon EOS 7D
# Canon EOS 50D
# Canon EOS 60D
# Canon EOS 550D
# Canon EOS 650D

bracket_mode() {
    local bracket_mode
    local exposure
    read bracket_mode exposure <<<$(exiftool -n -S -t -MakerNotes:BracketMode -MakerNotes:AEBBracketValue "$1")
    
    if [ $bracket_mode = 1 ]; then
        echo "YES" "$exposure"
        return
    fi
    
    echo "NO" "0"
}

bracket_count() {
    local bracket_count=`exiftool -n -S -t -MakerNotes:AEBShotCount "$1" | cut -f1 -d' '`
    
    if [ ! -z "$bracket_count" ]; then
        echo $bracket_count
        return
    fi
    
    echo 3
}