#!/bin/bash

# Сводим брекетинг
 
SELF="`basename $0`"
SELF_PATH="`dirname $0`"

. "$SELF_PATH/functions.sh"

DIR="$1"
EXT="$2"

ENFUSE=`which enfuse`
EXIFTOOL=`which exiftool`

QUIET=0
VERBOSE=1
DRYRUN=N

# Фикс для пробелов в именах
IFS=$'\n'

if [ -z "$ENFUSE" ]; then
    echo "Для работы необходим пакет enblend"
    exit
fi

if [ -z "$EXIFTOOL" ]; then
    echo "Для работы необходим exiftool"
    exit
fi

if [ -z "$DIR" ]; then
    echo "Укажите каталог с файлами"
    exit
fi

if [ -z "$EXT" ]; then
    echo "Укажите расширение файлов"
    exit
fi

if [ ! -d "$DIR" ]; then
    echo "$DIR не является директорией"
    exit
fi

DIR=$(cd "$DIR" && pwd) #transform to absolute path

BLEND_DIR="$DIR/blend"
BRACKETED_DIR="$DIR/bracketed"


blendTifFiles() {
    echo "Enfuse $1 $2 $3 in '$DIR'"
    local blend_name
    local new_file
    
    if [ ! -d "$BLEND_DIR" ]; then
        mkdir "$BLEND_DIR"
    fi
    
    blend_name=`basename $1 | sed "s/\..*//g"`
    new_file="$DIR/blend/$blend_name.tif"
    
    $ENFUSE --compression=deflate -o "$new_file"  "$1" "$2" "$3"
    
    if [ $? -eq 0 ]; then
        $EXIFTOOL -overwrite_original -x Orientation -x Compression -tagsFromFile "$1" -EXIF:All --IFD1:All -IPTC:All "${new_file}" > /dev/null 2>&1
    
        return $E_NO_ERR
    else
        echo "Failed"
        return $E_UNKNOWN
    fi
}


# function processFileType() takes file extension as a param (case insensitive)
processFileType() {
    local space_status
    local file
    local make
    local make_lower
    local camera
    local camera_lower
    local isbracketed
    local element_count
    local index
    local image_number1
    local image_number2
    local image_number3
    local exp_comp1
    local exp_comp2
    local exp_comp3
    local has_errors=0
    
    local extension=$1

    #if [ $USEKDE = 1 ]; then
    #    qdbus $dbusRef setLabelText "Processing $extension files"
    #    echo "Analyzing $extension files" >>$tmpfile
    #fi
    if [ $QUIET = 0 ]; then
        echo "Analyzing $extension files"
    fi
    declare -a bracketed
    
    for file in `find "$DIR" -maxdepth 1 -type f -iname "*.$extension" -print | sort`; do # find files with the right extension in specified directory and sort names
        isbracketed="NO"
        make=`$EXIFTOOL -n -S -EXIF:Make "$file" | cut -d ' ' -f 2-` # retrieve make from EXIF
        make_lower=`echo "$make" | awk '{print tolower($0)}'`
        echo -e "$file"
        camera=`$EXIFTOOL -n -S -EXIF:Model "$file" | cut -d ' ' -f 2-` # retrieve camera model from EXIF
        camera_lower=`echo "$camera" | awk '{print tolower($0)}'`
        
        if [ $VERBOSE = 1 ]; then
            echo Camera make: $make        Camera model: $camera
        fi
        fn_loaded "bracket_mode" || . $SELF_PATH/camera/${make_lower// /_}/${camera_lower// /_}
        
        if [ $VERBOSE = 1 ]; then
            echo -n "Checking if file `basename $file` is bracketed ... "
        fi
        
        isbracketed=`bracket_mode "$file"`
        if [ "$isbracketed" = "YES" ]; then
            bracketed=( "${bracketed[@]}" "$file" )
        fi
        
        if [ $VERBOSE = 1 ]; then
            echo $isbracketed
        fi
    done
    
    element_count=${#bracketed[@]}
    if [ $VERBOSE = 1 ]; then
        echo "$element_count bracketed images found"
    fi
    index=0 # counter for looping in the array of files
    while [ $index -lt  $(($element_count-2)) ];do # have to have at least 3 files left
        check_space "$DIR"
        if [ ! $SPACE_STATUS -eq 0 ]; then
            echo "Закончилось место на диске. Выходим."
            return $E_NO_SPACE
        fi
        
        image_number1=`basename "${bracketed[$index]}" | sed "s/\..*//g" | sed "s/[^0-9]//g"` # retrieve image name without path and without extension
        # make sure the file number sequence is continuous and that they belong to the same bracket
        image_number2=`basename "${bracketed[$(($index+1))]}" | sed "s/\..*//g" | sed "s/[^0-9]//g"`
        image_number3=`basename "${bracketed[$(($index+2))]}" | sed "s/\..*//g" | sed "s/[^0-9]//g"`
        if [ $VERBOSE = 1 ]; then
            echo -n "Checking if images $image_number1 $image_number2 $image_number3 go together ... "
        fi
        if [ $((10#$image_number2)) = $((10#$image_number1+1)) ] && [ $((10#$image_number3)) = $((10#$image_number1+2)) ]; then
            exp_comp1=`get_exposure "${bracketed[$index]}"`
            exp_comp2=`get_exposure "${bracketed[$(($index+1))]}"`
            exp_comp3=`get_exposure "${bracketed[$(($index+2))]}"`

            if [ `echo "($exp_comp1 - $exp_comp2) == ($exp_comp3 - $exp_comp1)" | bc -q` = 1 ]; then
                if [ $VERBOSE = 1 ]; then
                    echo "YES"
                fi
                let "folderIndex = $folderIndex + 1" # increment folder index
                #currentDir=$DIR/$extension/$DIRPREFIX$folderIndex
                if [ $QUIET = 0 ]; then
                    echo "`basename "${bracketed[$index]}"`  \\"
                    echo "`basename "${bracketed[$(($index+1))]}"`   |> $DIRPREFIX$folderIndex - Exposures: $exp_comp2 $exp_comp1 $exp_comp3"
                    echo "`basename "${bracketed[$(($index+2))]}"`  /"
                    echo
                fi
                #if [ $USEKDE = 1 ]; then
                #    echo "`basename ${bracketed[$index]}`  \\" >>$tmpfile
                #    echo "`basename ${bracketed[$(($index+1))]}`   |> $DIRPREFIX$folderIndex - Exposures: $exp_comp2 $exp_comp1 $exp_comp3" >>$tmpfile
                #    echo "`basename ${bracketed[$(($index+2))]}`  /" >>$tmpfile
                #    echo
                #fi
                if [ "$DRYRUN" = "N" ]; then # if for real
                    blendTifFiles "${bracketed[$index]}" "${bracketed[$(($index+1))]}" "${bracketed[$(($index+2))]}" #blend bracketed
                    #mv ${bracketed[$index]} ${bracketed[$(($index+1))]} ${bracketed[$(($index+2))]} "$BRACKETED_DIR"
                    if [ ! $? -eq $E_NO_ERR ]; then
                        has_errors=$?
                    fi
                fi
                let "index = $index + 3"
            else
                if [ $VERBOSE = 1 ]; then
                    echo "NO"
                fi
                let "index = $index + 1"
            fi
        else
            if [ $VERBOSE = 1 ]; then
                echo "NO"
            fi
            let "index = $index + 1"
        fi
    done
    
    return $has_errors
}

check_space "$DIR"

if [ -f "$DIR/._blended" ]; then
    echo "Файлы в каталоге уже сведены. Пропускаем."
elif [ ! $SPACE_STATUS -eq 0 ]; then
    echo "Недостаточно места на диске. Пропускаем каталог"
else
    processFileType "$EXT"
    if [ $? -eq 0 ]; then
        # Только если процесс действительно завершился без ошибок
        touch "$DIR/._blended"
    fi
fi
