#!/bin/bash
# Ищем файлы с расширением $extension в каталоге $DIR и конвертируем в TIFF
 
SELF="`basename $0`"
SELF_PATH=$(cd "`dirname $0`" && pwd)

usage() {
    echo "USAGE: $SELF [-f] [-w] <path> <extension>"
    echo -e "Options:"
    echo -e "\t-f Принудительно сконвертировать (даже если каталог отмечен, как сконвертированный)"
    echo -e "\t-w Автоматически определять баланс белого каталога"
    echo "Params:"
    echo -e "\t <path>\tпуть к каталогу с RAW-файлами (ex. /home/user/dir1/), not a file name"
    echo -e "\t <extension>\tрасширение RAW-файлов в каталоге (ex. CR2)"
}

i=0
_agrs=()
for arg in "$@"; do
    _agrs[$i]="$arg"
    i=$((i + 1))
done

while getopts "fw" Option; do
    case $Option in
            f ) FORCE="-f";;
            w ) AUTOBB="1";;
            * ) echo "[!] Invalid option" && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

. "$SELF_PATH/functions.sh"

DIR="$1"
EXTENSION="$2"

BLEND_BRACKETED_BIN="$SELF_PATH/yhdt-blend-bracketed"

EXIFTOOL=`which exiftool`
UFRAW_BATCH=`which ufraw-batch`

IFS=$'\n'

if [ -z "$UFRAW_BATCH" ]; then
    echo "Для работы необходим UFRaw" && usage && exit 1
fi

if [ -z "$EXIFTOOL" ]; then
    echo "Для работы необходим exiftool" && usage && exit 1
fi

if [ -z "$DIR" ]; then
    echo "Укажите каталог с файлами" && usage && exit 1
fi

if [ ! -d "$DIR" ]; then
    echo "$DIR не является директорией" && usage && exit 1
fi

if [ -z "$EXTENSION" ]; then
    echo "Укажите расширение файлов" && usage && exit 1
fi

DIR=$(cd "$DIR" && pwd) #transform to absolute path

JPG_DIR="$DIR/jpg"
TIF_DIR="$DIR/_tif"

cr_count=`find "$DIR" -maxdepth 1 -type f -iname "*.$EXTENSION" -print | wc -l`

convertDirectory() {
    local space_status
    local image
    local ufraw_config="$DIR/img.ufraw"
    local wb
    declare -a images
    
    for image in `find "$DIR" -maxdepth 1 -type f -iname "*.$EXTENSION" -print | sort`; do
        images=( "${images[@]}" "$image" )
    done

    echo "Конвертирую каталог '$DIR'..."
    check_space_for_tifs ${#images[@]} "$DIR"
    if [ ! $SPACE_STATUS -eq 0 ]; then
        echo "Недостаточно места на диске. Выходим"
        return $E_NO_SPACE
    fi
  
    if [ ! -d "$JPG_DIR" ]; then
        mkdir "$JPG_DIR"
    fi
    
    if [ -d "$TIF_DIR" ]; then
        rm "$TIF_DIR" -rf
    fi
    mkdir "$TIF_DIR"

    find "$DIR" -maxdepth 1 -type f -iname "*.jpg" -exec mv {} "$JPG_DIR" \;
    
    if [ ! -z "$AUTOBB" ]; then
        if [ ! -f "$ufraw_config" ]; then
            $UFRAW_BATCH --create-id=only --out-type=tif --out-depth=16 --wb=auto --silent --overwrite --output="$DIR/img" "${images[0]}"
        fi
        
        local temp=`grep Temperature "$ufraw_config" | grep -P '[\d.]+' -o`
        local green=`grep Green "$ufraw_config" | grep -P '[\d.]+' -o`
        rm "$ufraw_config"
        
        wb="--temperature=$temp --green=$green"
    else
        if [ -f "$ufraw_config" ]; then
            local temp=`grep Temperature "$ufraw_config" | grep -P '[\d.]+' -o`
            local green=`grep Green "$ufraw_config" | grep -P '[\d.]+' -o`
            
            wb="--temperature=$temp --green=$green"
        else
            wb="--wb=camera"
        fi
    fi
    
    $UFRAW_BATCH $wb --out-path="$TIF_DIR" --out-type=tif --out-depth=16 --create-id=no \
            --zip --silent --overwrite "$DIR"/*.$EXTENSION
}

if [ ! -z "$FORCE" -a -f "$DIR/._converted" ]; then
    rm "$DIR/._converted"
fi

if [ -f "$DIR/._converted" ]; then
    echo "Файлы в каталоге '$DIR' уже сконвертированы. Пропускаем."
else
    # Пропускаем каталоги, в которых нет CR2
    if [ $cr_count -gt 0 ]; then
        convertDirectory
        if [ $? -eq 0 ]; then
            touch "$DIR/._converted"
        fi
    fi
fi

# И сразу сведем брекетинг уже из TIFF`ов
"$BLEND_BRACKETED_BIN" $FORCE "$TIF_DIR" "tif"
