#!/bin/bash

# Перебираем все подкаталоги внутри $DIR и запускаем конвертацию внутри каждого


SELF="`basename $0`"
SELF_PATH=$(cd "`dirname $0`" && pwd)

usage() {
    echo "USAGE: $SELF [-f] [-w] <path> <extension>"
    echo -e "Options:"
    echo -e "\t-f Принудительно сконвертировать (даже если каталог отмечен, как сконвертированный)"
    echo -e "\t-w Автоматически определять баланс белого каталога"
    echo "Params:"
    echo -e "\t <path>\tпуть к каталогу с RAW-файлами (ex. /home/user/dir1/), not a file name"
    echo -e "\t <extension>\tрасширение RAW-файлов в каталоге (ex. CR2)"
}

i=0
_agrs=()
for arg in "$@"; do
    _agrs[$i]="$arg"
    i=$((i + 1))
done

while getopts "fw" Option; do
    case $Option in
            f ) FORCE="-f";;
            w ) AUTOBB="-w";;
            * ) echo "[!] Invalid option" && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

. "$SELF_PATH/functions.sh"

DIR="$1"
EXTENSION="$2"

DIR_CONVERT_BIN="$SELF_PATH/yhdt-convert-directory"

# Фикс для пробелов в именах
IFS=$'\n'

if [ -z "$DIR" ]; then
    echo "Укажите каталог с файлами" && usage && exit 1
fi

if [ ! -d "$DIR" ]; then
    echo "$DIR не является директорией" && usage && exit 1
fi

if [ -z "$EXTENSION" ]; then
    echo "Укажите расширение файлов" && usage && exit 1
fi

DIR=$(cd "$DIR" && pwd) #transform to absolute path

LOCKFILE="$DIR/lock.$$"

# Ищем все папки по указанному пути и в каждой выполняем конвертацию
### если есть, что конвертировать
walkDirs() {
    local lf
    local pid
    local process
    local space_status
    
    local extension=$1
    
    for lf in `find "$DIR" -maxdepth 1 -type f -iname "lock.*" -print | sort`; do
        #echo "Lockfile: $lf"
        pid=`basename "$lf" | sed "s/^.*\.//ig"`
        #echo "PID: $pid"
        
        process=`ps -A | grep $pid | grep -v grep`
        #echo "Process: $Process"
        
        if [ ! -z "$process" ]; then
            echo "Каталог '$DIR' уже обрабатывается. Выходим"
            exit
        else
            echo "Потерянный lockfile. Удаляем"
            rm $lf
        fi
    done
    
    touch "$LOCKFILE"
    
    find "$DIR" -type d -print | sort | while read directory; do
        check_space "$directory"
        if [ ! $SPACE_STATUS -eq 0 ]; then
            echo "Недостаточно места для работы. Освободите как минимум ${MIN_SPACE_MB}МБ"
            return $E_NO_SPACE
        fi

        cr_count=`find "$directory" -maxdepth 1 -type f -iname "*.$extension" -print | wc -l`
        
        if [ ! "$cr_count" -eq 0 ]; then
            "$DIR_CONVERT_BIN" $FORCE $AUTOBB "$directory" "$extension"
        fi
    done
}

walkDirs "$EXTENSION"
rm "$LOCKFILE"
