#!/bin/sh

# Перебираем все подкаталоги внутри $DIR и запускаем конвертацию внутри каждого


SELF="`basename $0`"
SELF_PATH="`dirname $0`"


DIR="$1"
EXTENSION="$2"

DIR_CONVERT_BIN="$SELF_PATH/yhdt-convert-directory"

if [ -z "$DIR" ]; then
    echo "Укажите каталог с файлами"
    exit
fi

if [ ! -d "$DIR" ]; then
    echo "$DIR не является директорией"
    exit
fi

if [ -z "$EXTENSION" ]; then
    echo "Укажите расширение файлов"
    exit
fi

DIR=$(cd "$DIR" && pwd) #transform to absolute path

# Ищем все папки по указанному пути и в каждой выполняем конвертацию
### если есть, что конвертировать
walkDirs() {
    extension=$1
    
    for directory in `find "$DIR" -type d -print | sort`; do
        cr_count=`find "$directory" -maxdepth 1 -type f -iname "*.$extension" -print | wc -l`
        
        if [ ! "$cr_count" -eq 0 ]; then
            "$DIR_CONVERT_BIN" "$directory" "$extension"
        fi
    done
}

walkDirs "$EXTENSION"