#!/bin/bash
# Nikon D50
# Nikon D90

bracket_mode() {
    local bracket_mode
    local exposure
    read bracket_mode exposure <<<$(exiftool -n -S -t -MakerNotes:ShootingMode -MakerNotes:ExposureBracketValue "$1")
    
    let "bracket_mode = $bracket_mode & 16"
    if [ $bracket_mode = 16 ]; then
        echo "YES" "$exposure"
        return
    fi
    
    echo "NO" "0"
}

bracket_count() {
    echo 3
}